---
title: "Schedule"
---

*[W&B](https://2e.mindsmachine.com/) refers to the Watson & Breedlove text. Assignments are given in chapter:pages format, e.g., 1:2-19 means read Chapter 1, pages 2-19.*

## Week 1, August 21 - 25

### Mon, Aug 21

- Introduction to the course
- What is a system?
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 1:2-19.
    - Review <https://en.wikipedia.org/wiki/Systems_theory>
- Materials
    - | [HTML slides](lectures/260-2017-08-21.html) |

### Wed, Aug 23

- History of neuroscience
- Assignments
    - Review <http://www.columbia.edu/cu/psychology/courses/1010/mangels/neuro/history/history.html>.
    - Scan: <https://faculty.washington.edu/chudler/hist.html>
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-08-23-systems-history.html) |

### Fri, Aug 25

- Levels of analysis; neuroscience methods I
- Assignments
    - Read: [W&B](https://2e.mindsmachine.com/) 2:24, 26, 44-49, 3:53, 70-76.
    - Watch: [Beautiful 3-D Brain Scans Show Every Synapse](https://youtu.be/nvXuq9jRWKE)
    - Optional
        - [Grillner, Kozlov, Kotaleski (2005)](http://www.ncbi.nlm.nih.gov/pubmed/16146688)
        - [Powers of Ten](https://www.youtube.com/embed/0fKBhvDjuy0)
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-08-25-levels-methods.html) |

---

## Week 2, August 28 - September 1

### Mon, Aug 28

- Neuroscience methods II.
- Assignments
    - Watch: [Magnetic Resonance Imaging Explained](https://youtu.be/MiL0wCZr0Mw)
    - Optional: <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods>.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-08-28-functional-methods.html) |

### Wed, Aug 30

- Tour of [Social, Life, & Engineering Sciences Imaging Center (SLEIC)](http://imaging.psu.edu). Meet in lobby of [Chandlee Lab](http://www.psumap.com/#Chandlee%20Lab)

### Fri, Sep 1

- Neuroanatomy I
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/): 2:30-43.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-01-anatomy-I.html) |

---

## Week 3, September 4 - 8

### Mon, Sep 4

**Labor Day, NO CLASS**

### Wed, Sep 6

- Neuroanatomy II
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/): 2:30-43.
    - Read [W&B](https://2e.mindsmachine.com/): 2:20-29.
- Materials 
    - Lecture notes. | [HTML slides](lectures/260-2017-09-06-anatomy-II.html) |

### Fri, Sep 8

- **Quiz 1**. | [Answer key](quiz/psych-260-quiz-1-answers.pdf) | 
- Neuroanatomy III
- Neuroanatomy Lab

---

## Week 4, September 11 - 15

### Mon, Sep 11

- **MEET in 208 Chambers**
- Neuroanatomy Lab (continued) 

### Wed, Sep 13

- Cells of the nervous system
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/): 2:20-29.
    - Read [W&B](https://2e.mindsmachine.com/) 3:50-55.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-13-cells.html) |

### Fri, Sep 15

- Neurophysiology I
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 3:55-59.
    - Watch <https://www.youtube.com/embed/PtKAeihnbv0>
 - Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-15-neurophys-I.html) |
   
---

## Week 5, September 18 - 22

### Mon, Sep 18

- Neurophysiology II
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 3:59-69
 - Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-18-neurophys-II.html) |

### Wed, Sep 20

- Neurophysiology III
- Exam 1 review
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-20-neurophys-III.html) |
    - Study guide. | [HTML slides](lectures/260-2017-09-20-exam-1-review.html) |

### Fri, Sep 22
<!-- Rosh Hashana Day 2 -->
- **Exam 1**. | [Answer key](exam/psych-260-exam-1.ans.pdf) | 

---

## Week 6, September 25 - 29

### Mon, Sep 25

- Neurochemistry I
- Assignments
    -  Read [W&B](https://2e.mindsmachine.com/) 4:82-86
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-25-neurochem-I.html) |

### Wed, Sep 27

- Neurochemistry II
- Assignments
    -  Read [W&B](https://2e.mindsmachine.com/) 4:82-86
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-27-neurochem-II.html) |

### Fri, Sep 29

- Hormones and the brain
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 8:208-226
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-09-29-hormones.html) |

---

## Week 7, October 2 - 6

### Mon, Oct 2

- **Quiz 2**. | [Answer key](quiz/psych-260-quiz-2-ans.pdf) | 
- Exam 1 returned. | [Answer key](exam/psych-260-exam-1.ans.pdf) | 
- **Blog post 1 (of 3) due**. | [Assignment details](blog-assignment.html) |
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-02-exam-1-returned.html) |

### Wed, Oct 4

- Evolution of the human brain.
- Assignments
    - Read [Hofman 2014](http://www.frontiersin.org/Journal/Abstract.aspx?s=742&name=neuroanatomy&ART_DOI=10.3389/fnana.2014.00015).
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-04-evolution.html) |

### Fri, Oct 6

- Development of the brain
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-06-development.html) |

---
    
## Week 8, October 9 - 13

### Mon, Oct 9

- Development of the adolescent brain
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-09-development-II.html) |

### Wed, Oct 11

- Review for Exam 2
- Materials
    - Study guide. | [HTML slides](lectures/260-2017-10-11-exam-2-review.html) |

### Fri, Oct 13

- **Exam  2**. | [Answer key](exam/psych-260-exam-2.ans.pdf) |

---

## Week 9, October 16 - 20

### Mon, Oct 16

<!-- Jason lecturing -->
- Topic
    - Psychopathology I: Depression.
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 12:352-358.
- Materials
    - Lecture notes. | [PDF](lectures/Depression_Lecture 10.16.pptx.pdf) |
    
<!-- What do drug treatments do? Look at pop sci article; what does it get wrong? -->

### Wed, Oct 18

- Psychopathology II: Bipolar disorder.
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 12:358-359.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-18-bipolar.html) | [PDF](lectures/260-2017-10-18-bipolar.pdf) |
    
<!-- Find bio of famous person with bipolar; what do treatments actually do? -->

### Fri, Oct 20

- Psychopathology III: Schizophrenia.
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 12:338-352.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-20-schizophrenia.html) | [PDF](lectures/260-2017-10-20-schizophrenia.pdf) |

---

## Week 10, October 23 - 27

#### Mon, Oct 23

- Topic
    - Emotion
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 11:310-336
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-23-emotion-reward.html) | [PDF](lectures/260-2017-10-23-emotion-reward.pdf) |

### Wed, Oct 25

- Happiness & reward; fear & stress
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-25-happiness-reward-fear.html) | [PDF](lectures/260-2017-10-23-happiness-reward-fear.pdf) |

### Fri, Oct 27

- **Quiz 3**. | [Answer key](quiz/psych-260-quiz-3-ans.pdf) | 
- Exam 2 returned. | [Answer key](exam/psych-260-exam-2.ans.pdf) |
    - Lecture notes. | [HTML slides](lectures/psych-260-2017-10-27-exam-2-returned.html) | 
    
---

## Week 11, October 30 - November 3

### Mon, Oct 30

- Sensory systems
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 5:110-121
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-10-30-sensation.html) | [PDF](lectures/260-2017-10-30-sensation.pdf) |

### Wed, Nov 1

- Somatosensation
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 5:121-126; 6:162-164
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-01-somatosensation.html) | [PDF](lectures/260-2017-11-01-somatosensation.pdf) |

### Fri, Nov 3

- Pain
- Assignments
    - **Blog post #2 (of 3) due**. | [Assignment details](blog-assignment.html) |
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-03-pain.html) | [PDF](lectures/260-2017-11-03-pain.pdf) |
    
---

## Week 12, November 6 - 10

### Mon, Nov 6

- Action
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 5:126-143
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-06-action.html) | [PDF](lectures/260-2017-11-06-action.pdf) |

### Wed, Nov 8

- Action II
- Exam 3 review
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-08-action-II.html) | [PDF](lectures/260-2017-11-08-action-II.pdf) |
    - Study guide. | [HTML slides](lectures/260-2017-11-08-exam-3-review.html) | [PDF](lectures/260-2017-11-08-exam-3-review.pdf) |

### Fri, Nov 10

- **Exam 3**.

---

## Week 13, November 13 - 17

### Mon, Nov 13

- Audition
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 6:144-162
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-13-audition.html) | [PDF](lectures/260-2017-11-13-audition.pdf) |

### Wed, Nov 15

- Vision
- Assignments
    - Read [W&B](https://2e.mindsmachine.com/) 7:174-185.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-15-vision.html) | [PDF](lectures/260-2017-11-15-vision.pdf) |
    - [Extra credit opportunity](lectures/260-2017-11-15-extra-credit.html)

### Fri, Nov 17

**NO CLASS**
<!-- - Vision II. -->
<!-- - Assignments -->
<!--     - Read [W&B](https://2e.mindsmachine.com/) 7:185-207. -->

---

## Thanksgiving Break, November 20 - 24

**NO CLASSES**

---

## Week 14, November 27 - December 1

### Mon, Nov 27

- Wrap up on vision
- Learning & memory
- Assignments
    - Read 13:368-383
- **Papers or blog post #3 (of 3) due**. | [Blog assignment details](blog-assignment.html) | [Paper assignment details](paper-assignment.html) |
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-27-vision-II.html) | [PDF](lectures/260-2017-11-27-vision-II.pdf) |

### Wed, Nov 30

- Learning & memory II
- Assignments
    - Read 13:368-383-393
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2017-11-29-memory.html) | [PDF](lectures/260-2017-11-29-memory.pdf) |

### Fri, Dec 1

- **Quiz 4**.
- Exam 3 returned. | [Answer key](exam/psych-260-exam-3-ans.pdf) |
    - Lecture notes. | [HTML slides](lectures/260-2017-12-01-exam-3-returned.html) | 

---

## Week 15, December 4 - 8

### Mon, Dec 4

- Speed of nervous system conduction lab
    - Lecture notes. | [HTML slides](lectures/260-2017-12-04-speed-lab.html) | 

### Wed, Dec 6

- Review for Exam 4
- Materials
    - Study guide. | [HTML slides](lectures/260-2017-12-06-exam-4-study-guide.html) | [PDF](lectures/260-2017-12-06-exam-4-study-guide.pdf) |

### Fri, Dec 8

- The Cerebral Symphony
- Materials
    - [HTML slides](lectures/260-2017-12-08-cerebral-symphony.html)

---
    
## Finals Week, December 11 - 15

### Mon, Dec 11 

- **12:20-2:10 pm in 302 Boucke**